esphome:
  name: iot-getting-started
  friendly_name: IoT Getting Started

esp8266:
  board: d1_mini

# Enable logging
logger:

ota:
  password: "204fd9489934ff4d24909949bdb3bdb6"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_password_2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Iot-Getting-Started"
    password: "C0VoOIqD2eWk"

captive_portal:

web_server:
